"""Add GIN indexes for JSONB fields

Revision ID: 3fb2b205789b
Revises: 5a3c7457e4ee
Create Date: 2025-03-07 22:48:13.574056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb2b205789b'
down_revision: Union[str, None] = '5a3c7457e4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_demographics_categorical_characteristics', 'demographics', ['categorical_characteristics'], unique=False, postgresql_using='gin')
    op.create_index('ix_demographics_numerical_characteristics', 'demographics', ['numerical_characteristics'], unique=False, postgresql_using='gin')
    op.create_index('ix_questions_options', 'questions', ['options'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questions_options', table_name='questions', postgresql_using='gin')
    op.drop_index('ix_demographics_numerical_characteristics', table_name='demographics', postgresql_using='gin')
    op.drop_index('ix_demographics_categorical_characteristics', table_name='demographics', postgresql_using='gin')
    # ### end Alembic commands ###
