"""Add num_agents to Demographics

Revision ID: 5a3c7457e4ee
Revises: 640d535a31d0
Create Date: 2025-03-07 22:23:25.574502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3c7457e4ee'
down_revision: Union[str, None] = '640d535a31d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('num_agents', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographics', 'num_agents')
    # ### end Alembic commands ###
