"""Added GIN index for agents table

Revision ID: 640d535a31d0
Revises: ef0a3513fc9e
Create Date: 2025-03-07 18:57:04.719719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640d535a31d0'
down_revision: Union[str, None] = 'ef0a3513fc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agents_categorical_characteristics', 'agents', ['categorical_characteristics'], unique=False, postgresql_using='gin')
    op.create_index('ix_agents_numerical_characteristics', 'agents', ['numerical_characteristics'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agents_numerical_characteristics', table_name='agents', postgresql_using='gin')
    op.drop_index('ix_agents_categorical_characteristics', table_name='agents', postgresql_using='gin')
    # ### end Alembic commands ###
